captcha:
  solver-service: "anti-captcha.com" # Or capmonster.cloud
  solver-key: ""

settings:
  invite_code: "https://discord.gg/YNQxaWw7"
  threads: 5 
  rotating_proxy: "" # Format is username:password@host:port or host:port

token:MTIwNTAyOTc0NjMyOTY1NzQ4NQ.GNe2dg.xcoYjhJ8TNNC_7U_rbCejnCka4L9cY34FJ3ycY
  username: "AR15" # Leave empty for random
